name: Apollo service checks

inputs:
  action:
    required: true
  localSchemaFile:
    required: true
  key:
    required: true
  variant:
    required: true
  serviceName:
    required: true
  serviceURL:
    required: false
  codegenGitStatusPaths:
    required: false
    default: ''
  codegenScript:
    required: false
    default: 'npm run codegen'
  graphName:
    required: false
    default: 'apfm-hydra'

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if [[ ${{ inputs.action }} = service:check ]]; then
          ${{ inputs.codegenScript }}
          if [[ -z "$(git status ${{ inputs.codegenGitStatusPaths }} --porcelain)" ]]; then
            echo "Codegen is up to date, all types and schemas validated."
          else
            echo "Ran codegen and found changes! Exiting."
            git status
            exit 1
          fi
        fi

    - shell: bash
      run: |
        if [[ ${{ inputs.action }} = service:check ]]; then
          APOLLO_KEY=${{ inputs.key }} npx @apollo/rover@0.10.0 subgraph check ${{ inputs.graphName }}@${{ inputs.variant }} \
            --name=${{ inputs.serviceName }}
            --schema=${{ inputs.localSchemaFile }}

        elif [[ ${{ inputs.action }} = service:push ]]; then
          APOLLO_KEY=${{ inputs.key }} npx @apollo/rover@0.10.0 subgraph publish ${{ inputs.graphName }}@${{ inputs.variant }} \
            --name=${{ inputs.serviceName }} \
            --schema=${{ inputs.localSchemaFile }} \
            --routing-url=${{ inputs.serviceURL }} \
            --convert
        else
          echo "Must specify an action of 'service:push' or 'service:check', found '${{ inputs.action }}'. Exiting."
          exit 1
        fi
